//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopUsuarios.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Usuarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Usuarios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkshopUsuarios.Resources.Usuarios", typeof(Usuarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string TextoApellidoMaterno {
            get {
                return ResourceManager.GetString("TextoApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string TextoApellidoPaterno {
            get {
                return ResourceManager.GetString("TextoApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Usuario.
        /// </summary>
        public static string TextoBotonNuevoUsuario {
            get {
                return ResourceManager.GetString("TextoBotonNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string TextoBuscar {
            get {
                return ResourceManager.GetString("TextoBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string TextoEdad {
            get {
                return ResourceManager.GetString("TextoEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string TextoEmail {
            get {
                return ResourceManager.GetString("TextoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string TextoNombre {
            get {
                return ResourceManager.GetString("TextoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda de Usuarios.
        /// </summary>
        public static string TituloBuscaUsuario {
            get {
                return ResourceManager.GetString("TituloBuscaUsuario", resourceCulture);
            }
        }
    }
}
